version: '3'

services:
  db:
    image: postgres

  open_auction:
    build: ../open_auction
    container_name: open_auction
    command: bundle exec puma -C config/puma.rb
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_HOST=db
    ports:
      - 3000:3000
    depends_on:
      - db
    tty: true
    stdin_open: true
    volumes:
      - .:/usr/src/app
      - bitbox:/usr/lib/bundler

volumes:
  bitbox:
