default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { '' } %>
  user: <%= ENV.fetch("POSTGRES_USERNAME") { '' } %>

development:
  <<: *default
  database: open_auction_development

test:
  <<: *default
  database: open_auction_test

production:
  <<: *default
  database: open_auction_production
